[package]
name = "trawlcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trawldb = { path = "../trawldb" }
clap = { version = "3.2.8", features = ["derive"] }
tokio = { version = "1", features = ["full"]}
